### ISSUE TITLE
add healthcheck

### ISSUE THREAD

**Issue by rshadow** [dr-co/pgpair#1]
please add healthcheck to enshure pg started

my example:
```
services:
  shard0:
    ...
    healthcheck:
      test: "pg_isready --host localhost --port 5432"
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 10s
```
